services:
  - type: web
    name: protein-folding
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: FIREBASE_KEY
        sync: false
      - key: HF_API_KEY
        sync: false
